-dontwarn org.jspecify.annotations.**
-dontwarn javax.annotation.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
-keep class org.jsoup.** { *; }
-dontwarn com.google.re2j.**
